// <auto-generated />
using System;
using MeshSMO.Sensors.Gateway.LocalStorage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeshSMO.Sensors.Gateway.Migrations
{
    [DbContext(typeof(LocalOutboxDbContext))]
    [Migration("20260908050811_AddGatewayIdentity")]
    partial class AddGatewayIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("MeshSMO.Sensors.Gateway.LocalStorage.GatewayIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("instance_id");

                    b.HasKey("Id");

                    b.ToTable("gateway_identity", (string)null);
                });

            modelBuilder.Entity("MeshSMO.Sensors.Gateway.LocalStorage.OutboxHealthProbe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("checked_at");

                    b.HasKey("Id");

                    b.ToTable("health_probe", (string)null);
                });

            modelBuilder.Entity("MeshSMO.Sensors.Gateway.LocalStorage.OutboxSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("captured_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("transport");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAt", "Id")
                        .HasDatabaseName("ix_telemetry_snapshots_captured_at");

                    b.ToTable("telemetry_snapshots", (string)null);
                });

            modelBuilder.Entity("MeshSMO.Sensors.Gateway.LocalStorage.SensorPollState", b =>
                {
                    b.Property<string>("SensorSlug")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("sensor_slug");

                    b.Property<DateTimeOffset>("LastPollStartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_poll_started_at");

                    b.HasKey("SensorSlug");

                    b.ToTable("sensor_poll_states", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
