// <auto-generated />
using System;
using MeshSMO.Sensors.Gateway.LocalStorage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeshSMO.Sensors.Gateway.Migrations
{
    [DbContext(typeof(LocalOutboxDbContext))]
    partial class LocalOutboxDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("MeshSMO.Sensors.Gateway.LocalStorage.OutboxHealthProbe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("checked_at");

                    b.HasKey("Id");

                    b.ToTable("health_probe", (string)null);
                });

            modelBuilder.Entity("MeshSMO.Sensors.Gateway.LocalStorage.OutboxReading", b =>
                {
                    b.Property<long>("SnapshotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("MetricKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("metric_key");

                    b.Property<double?>("NumericValue")
                        .HasColumnType("REAL")
                        .HasColumnName("numeric_value");

                    b.Property<string>("TextValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("text_value");

                    b.HasKey("SnapshotId", "MetricKey");

                    b.ToTable("telemetry_readings", (string)null);
                });

            modelBuilder.Entity("MeshSMO.Sensors.Gateway.LocalStorage.OutboxSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("captured_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("transport");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAt", "Id")
                        .HasDatabaseName("ix_telemetry_snapshots_captured_at");

                    b.ToTable("telemetry_snapshots", (string)null);
                });

            modelBuilder.Entity("MeshSMO.Sensors.Gateway.LocalStorage.OutboxReading", b =>
                {
                    b.HasOne("MeshSMO.Sensors.Gateway.LocalStorage.OutboxSnapshot", null)
                        .WithMany("Readings")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeshSMO.Sensors.Gateway.LocalStorage.OutboxSnapshot", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
