// <auto-generated />
using System;
using MeshSMO.Sensors.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeshSMO.Sensors.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SensorsDbContext))]
    [Migration("20260908050700_NamespaceGatewayTelemetryByGateway")]
    partial class NamespaceGatewayTelemetryByGateway
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeshSMO.Sensors.Domain.Measurements.MeasurementSample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Extra")
                        .HasColumnType("jsonb")
                        .HasColumnName("extra");

                    b.Property<DateTimeOffset?>("MeasuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at");

                    b.Property<string>("ProtocolId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("protocol_id");

                    b.Property<byte[]>("RawPayload")
                        .HasColumnType("bytea")
                        .HasColumnName("raw_payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<long?>("RequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("request_id");

                    b.Property<int?>("RoundTripMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("round_trip_ms");

                    b.Property<float?>("Rssi")
                        .HasColumnType("real")
                        .HasColumnName("rssi");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<float?>("Snr")
                        .HasColumnType("real")
                        .HasColumnName("snr");

                    b.HasKey("Id");

                    b.HasIndex("SensorId", "ReceivedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_measurement_samples_sensor_received");

                    b.HasIndex("SensorId", "RequestId")
                        .IsUnique()
                        .HasDatabaseName("ux_measurement_samples_sensor_request");

                    b.ToTable("measurement_samples", (string)null);
                });

            modelBuilder.Entity("MeshSMO.Sensors.Domain.Measurements.MeasurementValue", b =>
                {
                    b.Property<Guid>("SampleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sample_id");

                    b.Property<string>("MetricKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("metric_key");

                    b.Property<double?>("NumericValue")
                        .HasColumnType("double precision")
                        .HasColumnName("numeric_value");

                    b.Property<string>("Quality")
                        .HasColumnType("text")
                        .HasColumnName("quality");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<string>("TextValue")
                        .HasColumnType("text")
                        .HasColumnName("text_value");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("SampleId", "MetricKey");

                    b.HasIndex("SensorId", "MetricKey", "Timestamp")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_measurement_values_sensor_metric_timestamp");

                    b.ToTable("measurement_values", (string)null);
                });

            modelBuilder.Entity("MeshSMO.Sensors.Domain.Polling.PollAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("request_id");

                    b.Property<int?>("RoundTripMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("round_trip_ms");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SensorId", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_poll_attempts_sensor_started");

                    b.HasIndex("SensorId", "RequestId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_poll_attempts_sensor_request_attempt");

                    b.ToTable("poll_attempts", (string)null);
                });

            modelBuilder.Entity("MeshSMO.Sensors.Domain.Sensors.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationPrecision")
                        .HasColumnType("text")
                        .HasColumnName("location_precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("MeshPublicKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mesh_public_key");

                    b.Property<int>("PollIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("poll_interval_seconds");

                    b.Property<int>("PollMaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("poll_max_attempts");

                    b.Property<int>("PollTimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("poll_timeout_seconds");

                    b.Property<string>("ProtocolId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("protocol_id");

                    b.Property<bool>("PublicIndexable")
                        .HasColumnType("boolean")
                        .HasColumnName("public_indexable");

                    b.Property<bool>("PublicVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("public_visible");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MeshPublicKey")
                        .IsUnique()
                        .HasDatabaseName("ux_sensors_mesh_public_key");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_sensors_slug");

                    b.ToTable("sensors", (string)null);
                });

            modelBuilder.Entity("MeshSMO.Sensors.Domain.Sensors.SensorMetric", b =>
                {
                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<string>("MetricKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("metric_key");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("Unit")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("unit");

                    b.HasKey("SensorId", "MetricKey");

                    b.ToTable("sensor_metrics", (string)null);
                });

            modelBuilder.Entity("MeshSMO.Sensors.Domain.Sensors.SensorStatusSnapshot", b =>
                {
                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failures");

                    b.Property<DateTimeOffset?>("LastPollAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_poll_at");

                    b.Property<float?>("LastRssi")
                        .HasColumnType("real")
                        .HasColumnName("last_rssi");

                    b.Property<float?>("LastSnr")
                        .HasColumnType("real")
                        .HasColumnName("last_snr");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SensorId");

                    b.ToTable("sensor_status", (string)null);
                });

            modelBuilder.Entity("MeshSMO.Sensors.Infrastructure.Persistence.GatewayTelemetrySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<Guid>("GatewayId")
                        .HasColumnType("uuid")
                        .HasColumnName("gateway_id");

                    b.Property<long>("GatewaySnapshotId")
                        .HasColumnType("bigint")
                        .HasColumnName("gateway_snapshot_id");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("transport");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAt")
                        .HasDatabaseName("ix_gateway_telemetry_snapshots_captured_at");

                    b.HasIndex("GatewayId", "GatewaySnapshotId")
                        .IsUnique()
                        .HasDatabaseName("ux_gateway_telemetry_gateway_id_snapshot_id");

                    b.ToTable("gateway_telemetry_snapshots", (string)null);
                });

            modelBuilder.Entity("MeshSMO.Sensors.Domain.Measurements.MeasurementSample", b =>
                {
                    b.HasOne("MeshSMO.Sensors.Domain.Sensors.Sensor", null)
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MeshSMO.Sensors.Domain.Measurements.MeasurementValue", b =>
                {
                    b.HasOne("MeshSMO.Sensors.Domain.Measurements.MeasurementSample", null)
                        .WithMany("Values")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeshSMO.Sensors.Domain.Sensors.Sensor", null)
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MeshSMO.Sensors.Domain.Polling.PollAttempt", b =>
                {
                    b.HasOne("MeshSMO.Sensors.Domain.Sensors.Sensor", null)
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MeshSMO.Sensors.Domain.Sensors.SensorMetric", b =>
                {
                    b.HasOne("MeshSMO.Sensors.Domain.Sensors.Sensor", null)
                        .WithMany("Metrics")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeshSMO.Sensors.Domain.Sensors.SensorStatusSnapshot", b =>
                {
                    b.HasOne("MeshSMO.Sensors.Domain.Sensors.Sensor", null)
                        .WithOne()
                        .HasForeignKey("MeshSMO.Sensors.Domain.Sensors.SensorStatusSnapshot", "SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeshSMO.Sensors.Domain.Measurements.MeasurementSample", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("MeshSMO.Sensors.Domain.Sensors.Sensor", b =>
                {
                    b.Navigation("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
