<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MeshSMO.Sensors.Domain\MeshSMO.Sensors.Domain.csproj" />
    <ProjectReference Include="..\..\src\MeshSMO.Sensors.Application\MeshSMO.Sensors.Application.csproj" />
    <ProjectReference Include="..\..\src\MeshSMO.Sensors.Forecasting\MeshSMO.Sensors.Forecasting.csproj" />
    <ProjectReference Include="..\..\src\MeshSMO.Sensors.Gateway\MeshSMO.Sensors.Gateway.csproj" />
    <ProjectReference Include="..\..\src\MeshSMO.Sensors.Web\MeshSMO.Sensors.Web.csproj" />
    <ProjectReference Include="..\..\src\MeshSMO.Sensors.Infrastructure\MeshSMO.Sensors.Infrastructure.csproj" />
  </ItemGroup>

</Project>
