services:
  sensor-migrator:
    image: ${MESHSMO_IMAGE_PREFIX:-ghcr.io/meshsmo}/meshsmo-sensors-dbmigrator:${MESHSMO_IMAGE_TAG:-latest}
    build: !reset null

  sensor-web:
    image: ${MESHSMO_IMAGE_PREFIX:-ghcr.io/meshsmo}/meshsmo-sensors-web:${MESHSMO_IMAGE_TAG:-latest}
    build: !reset null

  sensor-gateway:
    image: ${MESHSMO_IMAGE_PREFIX:-ghcr.io/meshsmo}/meshsmo-sensors-gateway:${MESHSMO_IMAGE_TAG:-latest}
    build: !reset null
