using System.Buffers.Binary;
using System.Net.Sockets;
using System.Text;
using System.Text.Json;
using Microsoft.Extensions.Options;

namespace MeshSMO.Sensors.Gateway.MeshCore;

/// <summary>
/// Poll channel that talks to a stock MeshCore companion radio over TCP
/// (Wi-Fi builds expose the companion frame protocol on port 5000) instead of
/// a MeshCoreTel repeater. Poll requests go out as CMD_SEND_BINARY_REQ — the
/// same ECDH-encrypted REQ packet the repeater sends from POST /api/request —
/// and the login bootstrap as CMD_SEND_LOGIN, falling back to
/// CMD_SEND_ANON_REQ when the node is not a contact of the radio yet
/// (firmware v13+ creates one automatically; the wire is the same
/// unique(4)+password login bootstrap).
///
/// Differences to the repeater channel, absorbed here so callers see the
/// repeater document shape: the 4-byte request timestamp is generated by the
/// companion firmware (the gateway prefix is stripped from the payload and
/// restored from the response tag into responseHex), and rssi/snr do not
/// exist in companion frames. The radio processes one request per type at a
/// time; commands are serialized with a lock.
/// </summary>
public sealed class CompanionRadioClient : IMeshNodeClient, IDisposable
{
    private const byte CmdSendLogin = 26;
    private const byte CmdSendBinaryReq = 50;
    private const byte CmdSendAnonReq = 57;

    private const byte RespCodeErr = 0x01;
    private const byte RespCodeSent = 0x06;
    private const byte PushCodeLoginSuccess = 0x85;
    private const byte PushCodeLoginFail = 0x86;
    private const byte PushCodeBinaryResponse = 0x8C;

    private const byte ErrCodeContactNotFound = 2;
    private const int PublicKeyPrefixBytes = 6; // PUB_KEY_SIZE on the command wire
    private const int TagBytes = 4;
    private const int MaximumLoginPasswordBytes = 15; // node ANON password limit
    private const int SentAckFrameLength = 10; // code + flooded + tag(4) + est_timeout(4)

    private readonly MeshCoreCompanionOptions _options;
    private readonly SemaphoreSlim _commandLock = new(1, 1);
    private readonly ILogger<CompanionRadioClient> _logger;
    private TcpClient? _client;
    private NetworkStream? _stream;

    public CompanionRadioClient(IOptions<MeshCoreOptions> options, ILogger<CompanionRadioClient> logger)
    {
        _options = options.Value.Companion;
        _logger = logger;
    }

    public string TransportName => "companion-tcp";

    public async Task<JsonDocument> SendAcquisitionRequestAsync(
        string destinationHex,
        string payloadHex,
        int timeoutMilliseconds,
        CancellationToken cancellationToken)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(destinationHex);
        ArgumentException.ThrowIfNullOrWhiteSpace(payloadHex);

        var destination = ParsePublicKeyPrefix(destinationHex);
        var payload = Convert.FromHexString(payloadHex);
        // The firmware prepends its own tag to the REQ body, so the gateway
        // timestamp prefix (the repeater /api/request wire) is dropped here
        // and restored from the response tag on the way back.
        var body = payload.Length > TagBytes ? payload[TagBytes..] : payload;

        await _commandLock.WaitAsync(cancellationToken).ConfigureAwait(false);
        try
        {
            var startedAt = DateTimeOffset.UtcNow;
            var deadline = startedAt + TimeSpan.FromMilliseconds(timeoutMilliseconds);
            await EnsureConnectedAsync(cancellationToken).ConfigureAwait(false);

            var ack = await SendCommandAsync(
                BuildCommandFrame(CmdSendBinaryReq, destination, body),
                deadline,
                cancellationToken).ConfigureAwait(false);
            if (ack.Tag is null)
                return AckDocument(ack.ErrorCode, startedAt);

            return await WaitForTaggedResponseAsync(ack, deadline, startedAt, cancellationToken)
                .ConfigureAwait(false);
        }
        finally
        {
            _commandLock.Release();
        }
    }

    public async Task<JsonDocument> SendAcquisitionLoginAsync(
        string destinationHex,
        string password,
        int timeoutMilliseconds,
        CancellationToken cancellationToken)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(destinationHex);
        ArgumentNullException.ThrowIfNull(password);

        var destination = ParsePublicKeyPrefix(destinationHex);
        var passwordBytes = EncodePassword(password);

        await _commandLock.WaitAsync(cancellationToken).ConfigureAwait(false);
        try
        {
            var startedAt = DateTimeOffset.UtcNow;
            var deadline = startedAt + TimeSpan.FromMilliseconds(timeoutMilliseconds);
            await EnsureConnectedAsync(cancellationToken).ConfigureAwait(false);

            var ack = await SendCommandAsync(
                BuildCommandFrame(CmdSendLogin, destination, passwordBytes),
                deadline,
                cancellationToken).ConfigureAwait(false);
            if (ack.Tag is not null)
                return await WaitForLoginPushAsync(destination, deadline, startedAt, cancellationToken)
                    .ConfigureAwait(false);

            if (ack.ErrorCode == ErrCodeContactNotFound)
            {
                // No contact on the radio: CMD_SEND_ANON_REQ (firmware v13+)
                // auto-creates one and puts unique(4)+password on the air — the
                // same wire as the login bootstrap of POST /api/login. The node
                // answer arrives as a tagged binary response, not a login push.
                _logger.LogInformation(
                    "Companion radio has no contact for {PubKeyPrefix}; retrying the login as an anonymous request",
                    destinationHex[..12]);
                ack = await SendCommandAsync(
                    BuildCommandFrame(CmdSendAnonReq, destination, passwordBytes),
                    deadline,
                    cancellationToken).ConfigureAwait(false);
                if (ack.Tag is null)
                    return AckDocument(ack.ErrorCode, startedAt);

                return await WaitForTaggedLoginResponseAsync(ack.Tag.Value, deadline, startedAt, cancellationToken)
                    .ConfigureAwait(false);
            }

            return AckDocument(ack.ErrorCode, startedAt);
        }
        finally
        {
            _commandLock.Release();
        }
    }

    public void Dispose()
    {
        _commandLock.Dispose();
        DisposeConnection();
    }

    /// <summary>
    /// Writes one command and reads frames until the device answers with
    /// RESP_CODE_SENT (carrying the firmware-assigned tag) or RESP_CODE_ERR.
    /// A quiet device counts as an ack timeout (Tag = null, ErrorCode = null).
    /// </summary>
    private async Task<CommandAck> SendCommandAsync(byte[] frame, DateTimeOffset deadline, CancellationToken cancellationToken)
    {
        await WriteFrameAsync(frame, cancellationToken).ConfigureAwait(false);

        while (true)
        {
            var reply = await ReadFrameAsync(deadline, cancellationToken).ConfigureAwait(false);
            if (reply is null)
                return new CommandAck(null, null, false);

            if (reply.Length >= SentAckFrameLength && reply[0] == RespCodeSent)
            {
                return new CommandAck(
                    BinaryPrimitives.ReadUInt32LittleEndian(reply.AsSpan(2)),
                    null,
                    reply[1] != 0);
            }

            if (reply.Length >= 2 && reply[0] == RespCodeErr)
            {
                _logger.LogWarning(
                    "Companion radio rejected command 0x{Command:X2} with error code {ErrorCode}",
                    frame[0],
                    reply[1]);
                return new CommandAck(null, reply[1], false);
            }

            LogDroppedFrame(reply);
        }
    }

    /// <summary>
    /// Waits for the node's answer to a poll request: PUSH_CODE_BINARY_RESPONSE
    /// with the tag from RESP_CODE_SENT. The tag holds the request timestamp
    /// echoed by the node, so responseHex is rebuilt as tag(4 LE) + body — the
    /// same shape the repeater returns from POST /api/request.
    /// </summary>
    private async Task<JsonDocument> WaitForTaggedResponseAsync(
        CommandAck ack,
        DateTimeOffset deadline,
        DateTimeOffset startedAt,
        CancellationToken cancellationToken)
    {
        var tag = ack.Tag!.Value;
        while (true)
        {
            var reply = await ReadFrameAsync(deadline, cancellationToken).ConfigureAwait(false);
            if (reply is null)
                return BuildStatusDocument("timeout", startedAt);

            if (reply.Length >= 2 + TagBytes && reply[0] == PushCodeBinaryResponse &&
                BinaryPrimitives.ReadUInt32LittleEndian(reply.AsSpan(2)) == tag)
            {
                var body = reply.AsSpan(2 + TagBytes);
                var response = new byte[TagBytes + body.Length];
                BinaryPrimitives.WriteUInt32LittleEndian(response, tag);
                body.CopyTo(response.AsSpan(TagBytes));
                var responseHex = Convert.ToHexString(response).ToLowerInvariant();
                _logger.LogInformation(
                    "Companion radio received a {ByteCount}-byte answer for tag {Tag} (flooded: {Flooded})",
                    body.Length,
                    tag,
                    ack.Flooded);
                return BuildStatusDocument("ok", startedAt, responseHex: responseHex, flooded: ack.Flooded);
            }

            LogDroppedFrame(reply);
        }
    }

    /// <summary>Waits for PUSH_CODE_LOGIN_SUCCESS/FAIL matching the destination key prefix.</summary>
    private async Task<JsonDocument> WaitForLoginPushAsync(
        byte[] destination,
        DateTimeOffset deadline,
        DateTimeOffset startedAt,
        CancellationToken cancellationToken)
    {
        while (true)
        {
            var reply = await ReadFrameAsync(deadline, cancellationToken).ConfigureAwait(false);
            if (reply is null)
                return BuildStatusDocument("timeout", startedAt);

            if (reply[0] == PushCodeLoginSuccess && HasPublicKeyPrefix(reply, destination))
                return BuildStatusDocument("ok", startedAt);

            if (reply[0] == PushCodeLoginFail && HasPublicKeyPrefix(reply, destination))
                return BuildStatusDocument("auth_failed", startedAt);

            LogDroppedFrame(reply);
        }
    }

    /// <summary>
    /// Waits for the node's answer to the ANON_REQ login bootstrap (a tagged
    /// binary response whose body is the repeater-style login reply: "OK…"
    /// legacy or RESP_SERVER_LOGIN_OK = 0x00 new format).
    /// </summary>
    private async Task<JsonDocument> WaitForTaggedLoginResponseAsync(
        uint tag,
        DateTimeOffset deadline,
        DateTimeOffset startedAt,
        CancellationToken cancellationToken)
    {
        while (true)
        {
            var reply = await ReadFrameAsync(deadline, cancellationToken).ConfigureAwait(false);
            if (reply is null)
                return BuildStatusDocument("timeout", startedAt);

            if (reply.Length >= 2 + TagBytes && reply[0] == PushCodeBinaryResponse &&
                BinaryPrimitives.ReadUInt32LittleEndian(reply.AsSpan(2)) == tag)
            {
                var body = reply.AsSpan(2 + TagBytes);
                var loginAccepted = body.Length >= 2 && ((body[0] == (byte)'O' && body[1] == (byte)'K') || body[0] == 0x00);
                if (!loginAccepted)
                {
                    _logger.LogWarning(
                        "Companion radio login bootstrap was rejected by the node ({ByteCount}-byte reply)",
                        body.Length);
                    return BuildStatusDocument("auth_failed", startedAt);
                }

                return BuildStatusDocument("ok", startedAt);
            }

            LogDroppedFrame(reply);
        }
    }

    private async Task EnsureConnectedAsync(CancellationToken cancellationToken)
    {
        if (_client is { Connected: true })
            return;

        DisposeConnection();
        var client = new TcpClient();
        try
        {
            using var timeout = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
            timeout.CancelAfter(TimeSpan.FromSeconds(_options.ConnectTimeoutSeconds));
            await client.ConnectAsync(_options.Host, _options.Port, timeout.Token).ConfigureAwait(false);
        }
        catch (OperationCanceledException) when (!cancellationToken.IsCancellationRequested)
        {
            client.Dispose();
            throw new IOException(
                $"The companion radio at {_options.Host}:{_options.Port} did not accept a connection " +
                $"within {_options.ConnectTimeoutSeconds}s.");
        }
        catch
        {
            client.Dispose();
            throw;
        }

        _client = client;
        _stream = client.GetStream();
        _logger.LogInformation("Connected to the companion radio at {Host}:{Port}", _options.Host, _options.Port);
    }

    private async Task WriteFrameAsync(byte[] frame, CancellationToken cancellationToken)
    {
        var stream = _stream ?? throw new InvalidOperationException("The companion radio connection is not open.");
        try
        {
            await stream.WriteAsync(CompanionFrameCodec.Encode(frame), cancellationToken).ConfigureAwait(false);
        }
        catch (Exception exception) when (exception is IOException or SocketException or ObjectDisposedException)
        {
            DisposeConnection();
            throw new IOException("The companion radio connection failed on write.", exception);
        }
    }

    /// <summary>
    /// Reads one complete device→host frame or returns null when the deadline
    /// passes first. Protocol violations drop the connection (the next call
    /// reconnects) because the stream position inside a frame is unrecoverable.
    /// </summary>
    private async Task<byte[]?> ReadFrameAsync(DateTimeOffset deadline, CancellationToken cancellationToken)
    {
        var stream = _stream ?? throw new InvalidOperationException("The companion radio connection is not open.");

        var header = new byte[CompanionFrameCodec.HeaderLength];
        if (!await TryReadExactAsync(stream, header, deadline, cancellationToken).ConfigureAwait(false))
            return null;
        if (header[0] != CompanionFrameCodec.DeviceToHostFlag)
        {
            DisposeConnection();
            throw new IOException($"The companion radio sent an unexpected frame flag 0x{header[0]:X2}.");
        }

        var length = header[1] | (header[2] << 8);
        if (length == 0 || length > CompanionFrameCodec.MaxFrameLength)
        {
            DisposeConnection();
            throw new IOException($"The companion radio sent an invalid frame length {length}.");
        }

        var frame = new byte[length];
        if (!await TryReadExactAsync(stream, frame, deadline, cancellationToken).ConfigureAwait(false))
            return null;

        return frame;
    }

    private async Task<bool> TryReadExactAsync(
        NetworkStream stream,
        byte[] buffer,
        DateTimeOffset deadline,
        CancellationToken cancellationToken)
    {
        var read = 0;
        while (read < buffer.Length)
        {
            var remaining = deadline - DateTimeOffset.UtcNow;
            if (remaining <= TimeSpan.Zero)
                return false;

            using var timeout = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
            timeout.CancelAfter(remaining);
            try
            {
                var count = await stream.ReadAsync(buffer.AsMemory(read), timeout.Token).ConfigureAwait(false);
                if (count == 0)
                {
                    DisposeConnection();
                    throw new IOException("The companion radio closed the connection.");
                }

                read += count;
            }
            catch (OperationCanceledException) when (!cancellationToken.IsCancellationRequested)
            {
                return false;
            }
            catch (Exception exception) when (exception is IOException or SocketException or ObjectDisposedException)
            {
                DisposeConnection();
                throw new IOException("The companion radio connection failed on read.", exception);
            }
        }

        return true;
    }

    private JsonDocument AckDocument(byte? errorCode, DateTimeOffset startedAt) =>
        errorCode is null
            ? BuildStatusDocument("timeout", startedAt)
            : BuildStatusDocument("error", startedAt, errorCode: errorCode);

    private static JsonDocument BuildStatusDocument(
        string status,
        DateTimeOffset startedAt,
        string? responseHex = null,
        byte? errorCode = null,
        bool? flooded = null)
    {
        var fields = new Dictionary<string, object?>(StringComparer.Ordinal)
        {
            ["status"] = status,
            ["elapsedMs"] = (int)(DateTimeOffset.UtcNow - startedAt).TotalMilliseconds,
        };
        if (responseHex is not null)
            fields["responseHex"] = responseHex;
        if (errorCode is not null)
            fields["errorCode"] = errorCode;
        if (flooded is not null)
            fields["flooded"] = flooded.Value;

        return JsonSerializer.SerializeToDocument(fields);
    }

    private static byte[] BuildCommandFrame(byte command, byte[] destination, ReadOnlySpan<byte> body)
    {
        var frame = new byte[1 + destination.Length + body.Length];
        frame[0] = command;
        destination.CopyTo(frame, 1);
        body.CopyTo(frame.AsSpan(1 + destination.Length));
        return frame;
    }

    private static byte[] ParsePublicKeyPrefix(string destinationHex)
    {
        byte[] fullKey;
        try
        {
            fullKey = Convert.FromHexString(destinationHex);
        }
        catch (Exception exception) when (exception is FormatException or ArgumentException)
        {
            throw new ArgumentException("The destination must be a hex-encoded public key.", nameof(destinationHex), exception);
        }

        if (fullKey.Length < PublicKeyPrefixBytes)
            throw new ArgumentException("The destination public key is too short.", nameof(destinationHex));

        return fullKey[..PublicKeyPrefixBytes];
    }

    private static byte[] EncodePassword(string password)
    {
        var bytes = Encoding.UTF8.GetBytes(password);
        if (bytes.Length > MaximumLoginPasswordBytes)
        {
            throw new ArgumentException(
                $"The node login password must be no longer than {MaximumLoginPasswordBytes} bytes in UTF-8.",
                nameof(password));
        }

        return bytes;
    }

    private static bool HasPublicKeyPrefix(byte[] frame, byte[] destination) =>
        // The firmware matches login pushes by the first 4 bytes of the contact key.
        frame.Length >= 2 + PublicKeyPrefixBytes &&
        frame.AsSpan(2, TagBytes).SequenceEqual(destination.AsSpan(0, TagBytes));

    private void LogDroppedFrame(byte[] frame) =>
        _logger.LogDebug("Dropping unexpected companion radio frame 0x{Code:X2} ({Length} bytes)", frame[0], frame.Length);

    private void DisposeConnection()
    {
        _stream?.Dispose();
        _stream = null;
        _client?.Dispose();
        _client = null;
    }

    private readonly record struct CommandAck(uint? Tag, byte? ErrorCode, bool Flooded);
}
