/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SensorsIndexRouteImport } from './routes/sensors.index'
import { Route as SensorsSlugRouteImport } from './routes/sensors.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsIndexRoute = SensorsIndexRouteImport.update({
  id: '/sensors/',
  path: '/sensors/',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsSlugRoute = SensorsSlugRouteImport.update({
  id: '/sensors/$slug',
  path: '/sensors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sensors/$slug': typeof SensorsSlugRoute
  '/sensors/': typeof SensorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sensors/$slug': typeof SensorsSlugRoute
  '/sensors': typeof SensorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sensors/$slug': typeof SensorsSlugRoute
  '/sensors/': typeof SensorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/sensors/$slug' | '/sensors/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/sensors/$slug' | '/sensors'
  id: '__root__' | '/' | '/about' | '/sensors/$slug' | '/sensors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SensorsSlugRoute: typeof SensorsSlugRoute
  SensorsIndexRoute: typeof SensorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors/': {
      id: '/sensors/'
      path: '/sensors'
      fullPath: '/sensors/'
      preLoaderRoute: typeof SensorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors/$slug': {
      id: '/sensors/$slug'
      path: '/sensors/$slug'
      fullPath: '/sensors/$slug'
      preLoaderRoute: typeof SensorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SensorsSlugRoute: SensorsSlugRoute,
  SensorsIndexRoute: SensorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
